---

- name: Delete any existing management pod
  k8s:
    name: "{{ meta.name }}-backup-manager"
    kind: Pod
    namespace: "{{ backup_pvc_namespace }}"
    state: absent
    force: true

- name: Remove ownerReferences from admin password secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ admin_password_name }}'
        namespace: '{{ meta.namespace }}'
        ownerReferences: null
  when:
    - admin_password_name is defined
    - admin_password_name | length

- name: Remove ownerReferences from db secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ db_secret_name }}'
        namespace: '{{ meta.namespace }}'
        ownerReferences: null
  when:
    - db_secret_name is defined
    - db_secret_name | length

- name: Remove ownerReferences from storage secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ storage_secret }}'
        namespace: '{{ meta.namespace }}'
        ownerReferences: null
  when:
    - storage_secret is defined
    - storage_secret | length

- name: Remove ownerReferences from container token secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ container_token_secret }}'
        namespace: '{{ meta.namespace }}'
        ownerReferences: null
  when:
    - container_token_secret is defined
    - container_token_secret | length
