---
- name: Create the pulp.pulpproject.org/v1alpha1.Pulp
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([crds_dir, cr_file])) | from_yaml }}"
  vars:
    cr_file: 'pulpproject_v1alpha1_pulp_cr.ci.yaml'

- name: Wait 5m for reconciliation to run
  k8s_info:
    api_version: '{{ custom_resource.apiVersion }}'
    kind: '{{ custom_resource.kind }}'
    namespace: '{{ namespace }}'
    name: '{{ custom_resource.metadata.name }}'
  register: cr
  until:
    - "'Successful' in (cr | json_query('resources[].status.conditions[].reason'))"
  delay: 6
  retries: 50
  vars:
    custom_resource: "{{ lookup('template', '/'.join([crds_dir, 'pulpproject_v1alpha1_pulp_cr.ci.yaml'])) | from_yaml }}"

- name: Add assertions here
  assert:
    that: true
    fail_msg: FIXME Add real assertions for your operator
