---
apiVersion: v1
kind: Secret
metadata:
  name: 'example-pulp-object-storage'
  namespace: 'default'
stringData:
  azure-account-name: 'myaccount'
  azure-account-key: 'mykey'
  azure-container: 'mycontainer'
  azure-container-path: 'mypath'
