---

# After copying secret files to the PVC, delete the local tmp copies
- name: Clean up _secrets directory
  file:
    path: "{{ secrets_dir.path }}"
    state: absent

- name: Delete any existing management pod
  k8s:
    name: "{{ meta.name }}-backup-manager"
    kind: Pod
    namespace: "{{ backup_pvc_namespace }}"
    state: absent
    force: true
