---

# After copying secret files to the PVC, delete the local tmp copies
- name: Clean up _secrets directory
  file:
    path: "{{ playbook_dir }}/_secrets"
    state: absent

- name: Delete any existing management pod
  k8s:
    name: "{{ meta.name }}-db-management"
    kind: Pod
    namespace: "{{ meta.namespace }}"
    state: absent
    force: true
