---

- name: Make _secrets directory
  file:
    path: "_secrets"
    state: directory
    mode: '0700'

- name: Template Pulp object definition
  template:
    src: pulp_object.yaml.j2
    dest: "_secrets/pulp_object.yaml"
    mode: '0600'

- name: Set Pulp object template file as var
  set_fact:
    pulp_object_template: "{{ lookup('file', '_secrets/pulp_object.yaml') }}"

- name: Write pulp object to pvc
  community.kubernetes.k8s_exec:
    namespace: "{{ meta.namespace }}"
    pod: "{{ meta.name }}-db-management"
    command: >-
      bash -c "echo '{{ pulp_object_template }}' > {{ _backup_dir }}/pulp_object.yaml"

- name: Get admin_password
  k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: '{{ pulp_admin_password_secret }}'
  register: _admin_password

- name: Set admin_password
  set_fact:
    admin_password: "{{ _admin_password['resources'][0]['data']['password'] | b64decode }}"

- name: Template admin_password definition
  template:
    src: admin_password_secret.yaml.j2
    dest: "_secrets/admin_password_secret.yaml"
    mode: '0600'

- name: Set admin_password template
  set_fact:
    admin_password_template: "{{ lookup('file', '_secrets/admin_password_secret.yaml') }}"

- name: Write secret_key to pvc
  community.kubernetes.k8s_exec:
    namespace: "{{ meta.namespace }}"
    pod: "{{ meta.name }}-db-management"
    command: >-
      bash -c "echo '{{ admin_password_template }}' > {{ _backup_dir }}/admin_password_secret.yaml"

- name: Get postgres configuration
  k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: '{{ postgres_configuration_secret }}'
  register: _postgres_configuration

- name: Set postgres configuration
  set_fact:
    database_password: "{{ _postgres_configuration['resources'][0]['data']['password'] | b64decode }}"
    database_username: "{{ _postgres_configuration['resources'][0]['data']['username'] | b64decode }}"
    database_name: "{{ _postgres_configuration['resources'][0]['data']['database'] | b64decode }}"
    database_port: "{{ _postgres_configuration['resources'][0]['data']['port'] | b64decode }}"
    database_host: "{{ _postgres_configuration['resources'][0]['data']['host'] | b64decode }}"
    database_type: "{{ _postgres_configuration['resources'][0]['data']['type'] | b64decode }}"

- name: Template postgres configuration definition
  template:
    src: postgres_secret.yaml.j2
    dest: "_secrets/postgres_secret.yaml"
    mode: '0600'

- name: Set postgres configuration
  set_fact:
    postgres_secret_template: "{{ lookup('file', '_secrets/postgres_secret.yaml') }}"

- name: Write secret_key to pvc
  community.kubernetes.k8s_exec:
    namespace: "{{ meta.namespace }}"
    pod: "{{ meta.name }}-db-management"
    command: >-
      bash -c "echo '{{ postgres_secret_template }}' > {{ _backup_dir }}/postgres_secret.yaml"
