apiVersion: pulp.pulpproject.org/v1beta1
kind: Pulp
metadata:
  name: example-pulp
spec:
  # image: pulp
  tag: "latest"
  pulp_admin_password_secret: "example-pulp-admin-password"
  pulp_storage_type: File
  pulp_file_storage:
    # k3s local-path requires this
    access_mode: "ReadWriteOnce"
    # We have a little over 10GB free on GHA VMs/instances
    size: "10Gi"
