apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pulps.pulp.pulpproject.org
spec:
  group: pulp.pulpproject.org
  names:
    kind: Pulp
    listKind: PulpList
    plural: pulps
    singular: pulp
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
