apiVersion: pulp.pulpproject.org/v1beta1
kind: Pulp
metadata:
  name: example-pulp
spec:
  pulp_storage:
    file:
      # This doesn't really matter for minikube. Single node by design,
      # but the storage provisioner allows for ReadWriteMany. So let's
      # stick to our default.
      access_mode: "ReadWriteMany"
      # The minikube VM won't go any larger.
      size: "375Gi"
