apiVersion: pulp.pulpproject.org/v1beta1
kind: Pulp
metadata:
  name: example-pulp
spec:
  image: galaxy
  image_web: "galaxy-web"
  tag: "latest"
  ingress_type: Ingress
  pulp_admin_password_secret: "example-pulp-admin-password"
  pulp_storage:
    file:
      # k3s local-path requires this
      access_mode: "ReadWriteOnce"
      # We have a little over 10GB free on GHA VMs/instances
      size: "10Gi"
