---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.kubernetes

  tasks:
    - import_tasks: resources.yml
      vars:
        state: absent

    - name: Destroy Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
        state: absent

    - name: Delete Custom Resource Definition
      k8s:
        definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/pulpproject_v1beta1_pulp_crd.yaml'])) }}"
        state: absent
        wait: yes
