---

- name: Set web protocol
  set_fact:
    web_protocol: "https"
  when:
    - ingress_tls_secret | length
    - route_tls_secret | length

- name: Set node address for ingress
  set_fact:
    content_origin: "{{ web_protocol }}://{{ pulp_hostname }}"
  when:
    - ingress_type|lower == "ingress"

- name: Set node address for route
  set_fact:
    content_origin: "{{ web_protocol }}://{{ route_host }}"
  when:
    - ingress_type|lower == "route"

- name: Look up the 1st address of the 1st node
  k8s_info:
    api_version: v1
    kind: Node
  register: k8s_nodes
  when:
    - content_origin is not defined

- name: DEBUG Show k8s_nodes
  debug:
    msg: "{{ k8s_nodes }}"
  when:
    - content_origin is not defined

- name: Set node address
  set_fact:
    content_origin: "http://{{ k8s_nodes.resources[0].status.addresses[0].address }}:24880"
  when:
    - content_origin is not defined

- name: Set content_origin
  set_fact:
    content_origin_dict: "{'content_origin': '{{ content_origin }}' }"

- name: DEBUG Show content_origin_dict
  debug:
    msg: "{{ content_origin_dict }}"

- name: merge content_origin with settings
  set_fact:
    pulp_default_settings: "{{ pulp_default_settings|combine(content_origin_dict) }}"

- name: DEBUG Show content_origin
  debug:
    msg: "{{ pulp_default_settings.content_origin }}"
