---
- set_fact:
    secret_key: "{{ lookup('password', '/dev/null length=50 chars=ascii_letters') }}"

- set_fact:
    file_storage: false
  when:
    - pulp_object_storage_s3_secret is defined or pulp_object_storage_s3_secret is defined

- name: pulp-file-storage persistent volume claim
  community.kubernetes.k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.pvc.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-file-storage
  when: file_storage

- include_tasks:
    file: s3-storage-configuration.yml
  when:
    - not file_storage
    - pulp_object_storage_s3_secret is defined
    - pulp_object_storage_s3_secret | length

- include_tasks:
    file: azure-storage-configuration.yml
  when:
    - not file_storage
    - pulp_object_storage_azure_secret is defined
    - pulp_object_storage_azure_secret | length

# Workaround being unable to do the following, for the subsequent task:
# when: (pulp_settings is not defined) or
#   (pulp_settings.content_origin is not defined)
# (short-circuit evaluation only works for multiple separate when statements)
# https://github.com/ansible/ansible/issues/50554
- name: Setting CONTENT_ORIGIN
  set_fact:
    content_origin_temp: pulp_settings.content_origin
  when:
    - pulp_settings is defined
    - pulp_settings.content_origin is defined

- name: Getting raw pulp_settings
  set_fact:
    raw_pulp_settings: "{{ raw_spec['pulp_settings'] | default({}) }}"
  when: pulp_settings is defined

- include_tasks:
    file: get_node_ip.yml
  when: content_origin_temp is not defined

- name: Combining pulp_settings
  set_fact:
    pulp_combined_settings: "{{ pulp_default_settings|combine(raw_pulp_settings, recursive=True) if pulp_settings is defined and pulp_settings is not none else pulp_default_settings }}"

- name: pulp-server secret
  community.kubernetes.k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.secret.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-server

- include_tasks:
    file: admin_password_configuration.yml

- name: pulp-api service
  community.kubernetes.k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.service.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-api

- name: Get information about the cluster
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"
  when:
  - not is_openshift
  - not is_k8s

- name: Determine the cluster type
  set_fact:
    is_openshift: "{{ True if 'route.openshift.io' in api_groups else False }}"
    is_k8s: "{{ False if 'route.openshift.io' in api_groups else True }}"
  when:
  - not is_openshift
  - not is_k8s

# Indicate what kind of cluster we are in (OpenShift or Kubernetes).
- debug:
    msg: "CLUSTER TYPE: is_openshift={{ is_openshift }}; is_k8s={{ is_k8s }}"
- fail:
    msg: "Cannot determine what type of cluster we are in"
  when:
  - not is_openshift
  - not is_k8s

- name: pulp-api deployment
  community.kubernetes.k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.deployment.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-api
